### ISSUE TITLE
Error: Cannot find module '@electron/remote/main'

### ISSUE THREAD

**Issue by kapitaali** [Dyalog/ride#918]
### Describe the issue you are having
Cannot start RIDE. When executing npm start, it errors:

```
- /home/xxx/Documents/Apps/ride/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/xxx/Documents/Apps/ride/main.js:6:13)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@electron/remote/main'
Require stack:
- /home/xxx/Documents/Apps/ride/main.js
- /home/xxx/Documents/Apps/ride/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/xxx/Documents/Apps/ride/main.js:6:13)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)

```

### Did you connect to an already running interpreter or start the interpreter from RIDE?
no

### How do you reproduce the issue?
I tried building RIDE as per the instructions. 

npm is installed via nvm

npm --version
8.19.2

npm version
{
  ride45: '4.5.0',
  npm: '8.19.2',
  node: '18.10.0',
  v8: '10.2.154.15-node.12',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.10',
  openssl: '3.0.5+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022b',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}

node --version
v18.10.0

nvm --version
0.34.0

**Comment by e9gille** [comment]
Try re-installing the node modules by first deleting the folder:
```
rm -rf node_modules
npm install
```
Also, we use the LTS version of node (currently v16.15.1 in the main branch).

**Comment by kapitaali** [comment]
Hi, the problem still persists. I did

```
nvm install --lts=Gallium
Installing with latest version of LTS line: Gallium
Downloading and installing node v16.17.1...
Downloading https://nodejs.org/dist/v16.17.1/node-v16.17.1-linux-x64.tar.xz...
##################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.17.1 (npm v8.15.0)

```

and rm -rf node_modules and npm i

but still getting the same error message.

**Comment by kapitaali** [comment]
Hi, my system is Debian Sid.

Linux 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 GNU/Linux
